#-------------------------------
# General Site Settings

menu:
- {name: 'Contenido', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'Acerca de',    url: 'about'}
- {name: 'Contacto',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Semana de la moda',   url: 'proj-1'}
- {name: 'VERSACE coleción primavera',   url: 'proj-2'}
- {name: 'Revista GQ', url: 'proj-3'}
- {name: 'Portada V MAGAZINE',  url: 'proj-4'}
- {name: 'Miss Sixty Spring',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/dempskars'}
- {icon: 'instagram', link: 'https://instagram.com/dempskars'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
